apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync 
  namespace: akv-test
spec:
  vault:
    name: kv-devops-devkeyvault # name of key vault
    object:
      name: campus-cache-redis # name of the akv object secret
      type: secret # akv object type
  output: 
    secret: 
      name: campus-cache-redis # kubernetes secret name
      dataKey: secret-value
