apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync 
  namespace: akv-demo
spec:
  vault:
    name: kv-devops-tstkeyvault # name of key vault
    object:
      contentType: application/x-json
      name: akv-demo # name of the akv object secret
      type: multi-key-value-secret # akv object type
  output: 
    secret: 
      name: akv-demo-secret # kubernetes secret name
